### ISSUE TITLE
If the description should modify (* Get the name of the pool, since we have to use that     * (and not the UUID) in the XML of the guest.

### ISSUE THREAD

**Issue by weikunzz** [libguestfs/libguestfs#28]
In the file https://github.com/libguestfs/libguestfs/blob/rhel-7.4/v2v/output_libvirt.ml, if the below words relate to the bug:https://bugzilla.redhat.com/show_bug.cgi?id=1141631,as we now support UUID we can modify the description.

(* Get the name of the pool, since we have to use that
    * (and not the UUID) in the XML of the guest.

**Comment by ptoscano** [comment]
The comment is correct, since only the name of a pool is allowed in the libvirt XML: the fix of the bug was exactly to always write the name, and not the UUID.

See commit 775e9cbd2a53c095518152c7a2a19f4044f0c91b.

PS: please report issues on the mailing list or in bugzilla, and not in the github issue tracker (which we don't use).
