### ISSUE TITLE
virt-list-filesystems for dmg is extension based. 

### ISSUE THREAD

**Issue by dbrezack** [libguestfs/libguestfs#47]
## Issue
The detection system for hfsplus file systems is based on extension. 

## Steps to reproduce 
```
$virt-list-filesystems -a HelloWorld.dmg -l
/dev/sda1 hfsplus
$mv HelloWorld.dmg HelloWorld.dmg_123
$virt-list-filesystems -a HelloWorld.dmg_123 -l
/dev/sda unknown
```

## Additional Comments
I'm not sure if the root cause of this is libguestfs or the underlying library as I'm not familiar with the repo
If it's not withing this library feel free to close and sorry for bothering ya'll

**Comment by ptoscano** [comment]
Thanks for using libguestfs!

This is why we recommend to use the `--format=FORMAT` option to explicitly specify the format of the image, instead of relying on autodetection:
```shell
$ virt-list-filesystems --format=dng -a HelloWorld.dmg -l
```

Also, since you mentioned it: please note that `virt-list-filesystems` is considered a deprecated tool. A better replacement, still part of libguestfs, is `virt-filesystems`:
```shell
$ virt-filesystems --format=dng -a HelloWorld.dmg -l
```
`virt-list-filesystems` might be removed in future versions of libguestfs.

**Comment by dbrezack** [comment]
Thanks @ptoscano  you've been a massive help!
