### ISSUE TITLE
is there a way to set discard=unmap when using guestmount?

### ISSUE THREAD

**Issue by braindevices** [libguestfs/libguestfs#52]
I cannot find anything in the document. This option is very important for dynamic qcow2 disks. Without out this the IO is super slow even on tmpfs only 3MB/s.

**Comment by rwmjones** [comment]
Not using guestmount, but it's possible to do it using the API directly and therefore from guestfish, something like this:
```
guestfish <<EOF
add disk.img discard:unmap
run
mount /dev/sda /
mount-local /tmp/mp
mount-local-run
EOF
```
See also: https://rwmj.wordpress.com/2012/03/29/libguestfs-mount-local/

**Comment by braindevices** [comment]
in 1.40.2 there is no discard:unmap, only disable/enable/besteffort 

I used `add test.qcow2 format:qcow2 discard:disable cachemode:unsafe` and `add test.qcow2 format:qcow2 discard:enable cachemode:unsafe`

both are quite slow:
discard:disable
```
$ time dd if=/dev/zero of=./largefile2 oflag=dsync bs=500MB count=1
1+0 records in
1+0 records out
500000000 bytes (500 MB, 477 MiB) copied, 16.9181 s, 29.6 MB/s

real    0m16.987s
user    0m0.001s
sys     0m1.591s
```
discard:enable
```
$ time dd if=/dev/zero of=./largefile2 oflag=dsync bs=500MB count=1
1+0 records in
1+0 records out
500000000 bytes (500 MB, 477 MiB) copied, 17.26 s, 29.0 MB/s

real    0m17.317s
user    0m0.000s
sys     0m1.474s
```

**Comment by rwmjones** [comment]
`enable` and `besteffort` are the same as discard=unmap on the qemu command line, see:
https://github.com/libguestfs/libguestfs/blob/fce82fe55a2b64a1a7e494858aa272d608e5e54e/lib/launch-direct.c#L227

In makes no sense to compare guestmount (FUSE-based) with qemu-nbd.  They are vastly different from each other, and guestmount in particular is known to be slow because of the many layers involved.
